---
title: "Fisher Exact Test"
author: "Adrian Goedeckemeyer"
date: "10/10/2016"
output: html_document
---

```{r}

fisher <- function(outcome_treatment, outcome_control, sharp_null, n) {
  observed_diff <- mean(outcome_treatment) - mean(outcome_control)
  effects <- c()
  
  for (experiment in 1:n){
    treat <- c()
    control <- c()
    for (element in outcome_treatment){
      if (sample(1:2, size = 1) == 1){
        treat <- c(treat, element)
      } else {
        control <- c(control, element + sharp_null)
      }
    }
    for (element in outcome_control){
      if (sample(1:2, size = 1) == 1){
        treat <- c(treat, element - sharp_null)
      } else {
        control <- c(control, element)
      }
    }
    if (length(control > 0 ) && length(treat) > 0){
      effects <- c(effects, mean(treat) - mean(control))
    }
  }
  plot(density(effects))
  abline(v=observed_diff, col="red")
  return(length(effects[effects > observed_diff])/length(effects))
}

```

```{r}
control_group <- c(55,72,72.7)
treatment_group <- c(70,66,78.9)
fisher(treatment_group, control_group, 0, 100)
```

# Gerber Green Imai

```{r}
require("Matching")
demo(GerberGreenImai)
summary(GerberGreenImai)
Y <- GerberGreenImai$VOTED98 #the outcome of interest
Tr <- GerberGreenImai$PHN.C1 #the treatment of interest
X <- cbind(GerberGreenImai$PERSONS, GerberGreenImai$VOTE96.1 ,GerberGreenImai$NEW ,GerberGreenImai$MAJORPTY ,GerberGreenImai$AGE ,GerberGreenImai$WARD)
BalanceMat <- cbind(GerberGreenImai$PERSONS, GerberGreenImai$VOTE96.1 ,GerberGreenImai$NEW ,GerberGreenImai$MAJORPTY ,GerberGreenImai$AGE ,GerberGreenImai$WARD)

genmatch <- GenMatch(Tr=Tr, X=X, BalanceMat=BalanceMat, pop.size=50, data.type.int=FALSE, print=0, replace=FALSE)
match <- Match(Y=Y, Tr=Tr, X=X, Weight.matrix=genmatch, replace=FALSE, caliper = c(10,10,10,10,0.1,10))
summary(match)
mb <- MatchBalance(GerberGreenImai$PHN.C1 ~ GerberGreenImai$PERSONS + GerberGreenImai$VOTE96.1 + GerberGreenImai$NEW + GerberGreenImai$MAJORPTY + GerberGreenImai$AGE + GerberGreenImai$WARD + GerberGreenImai$AGE2, match.out=match, nboots=500)
```

